name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install packages
      run: sudo apt-get install libgit2-dev
    
    - name: Clear binaries
      run: make clean
      
    - name: Make check
      run: make
      
